name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        arch: [aarch64, x86_64]
        host: [apple-darwin, unknown-linux-gnu, unknown-linux-musl]
        include:
          - os: ubuntu-latest
          - os: macos-latest
            host: apple-darwin
            
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: spawner
          target: ${{ matrix.arch }}-${{ matrix.host }}
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}